name: Publish order-command Docker
on:
  push:
    paths:
      - 'order-command-ms/**'
env:
  WORKDIR: order-command-ms
  DOCKERFILE: Dockerfile.multistage
  IMAGE_NAME: osowski/eda-order-command-ms
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump Versions
      uses: remorses/bump-version@js
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version_file: ${{ env.WORKDIR }}/VERSION
    - name: Build the Docker image
      run: |
        docker login -u ${DOCKER_U} -p ${DOCKER_P}
        cd ${WORKDIR}
        docker build . --file ${DOCKERFILE} --tag ${IMAGE_NAME}:$(cat VERSION)
        docker tag ${IMAGE_NAME}:$(cat VERSION) ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}
      env:
        DOCKER_U: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_P: ${{ secrets.DOCKER_PASSWORD }}
